apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernate-demo-api
  labels:
    app: kubernate-demo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernate-demo-api
  template:
    metadata:
      labels:
        app: kubernate-demo-api
    spec:
      containers:
        - name: kubernate-demo-api
          image: node-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20