apiVersion: v1
kind: Service
metadata:
  name: kubernate-demo-api
  labels:
    app: kubernate-demo-api
spec:
  selector:
    app: kubernate-demo-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort